# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-11 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='permissions',
            field=models.PositiveIntegerField(),
        ),
    ]
