# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-11 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_auto_20161111_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersms',
            old_name='type',
            new_name='group_name',
        ),
    ]
