# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-29 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0008_auto_20161112_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='section',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='usersms',
            name='roll_no',
        ),
    ]
