# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-29 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0010_auto_20161129_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50, null=True)),
                ('ugroup', models.CharField(max_length=50, null=True)),
                ('action', models.CharField(max_length=200, null=True)),
                ('datetime', models.DateTimeField()),
                ('ipAddress', models.CharField(max_length=200, null=True)),
                ('system', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
