# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-10 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0011_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='permissions',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='exam_permit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='hostel_permit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='review_permit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='student_permit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='users_permit',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
