# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-10 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0012_auto_20161210_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='users_permit',
            new_name='user_permit',
        ),
    ]
