# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-26 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdb',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='cd',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='cdname',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='cname',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='createdon',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='ddbank',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='dddate',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='ddno',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='emailid',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='form',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='isdd',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='isfee',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='isreg',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='mname',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='password',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='stat',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='state',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='subcat',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='updatedon',
        ),
        migrations.AddField(
            model_name='studentdb',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='enroll_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='father_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='mother_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='program_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='roll_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='school',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='sex',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
