# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0002_auto_20160926_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_num', models.CharField(max_length=100, null=True)),
                ('hostel_name', models.IntegerField(null=True)),
                ('room_num', models.CharField(max_length=100, null=True)),
                ('warden_name', models.CharField(max_length=200, null=True)),
                ('warden_mob', models.IntegerField(null=True)),
                ('caretaker_name', models.CharField(max_length=200, null=True)),
                ('caretaker_num', models.IntegerField(null=True)),
            ],
        ),
    ]
