# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0003_hostel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hostel',
            new_name='hostel_info',
        ),
    ]
