# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0004_auto_20160928_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_info',
            name='hostel_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
