# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-14 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0006_marks_status_marks_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks_status',
            old_name='roll_no',
            new_name='roll_num',
        ),
        migrations.RenameField(
            model_name='marks_subjects',
            old_name='roll_no',
            new_name='roll_num',
        ),
    ]
