# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-14 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0007_auto_20161014_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks_status',
            name='roll_num',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
