# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-17 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0008_auto_20161014_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('user', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
