# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-17 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0009_submitreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitreview',
            name='student',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
    ]
