# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-27 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0010_submitreview_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitreview',
            name='section',
            field=models.CharField(default='personal', max_length=100),
            preserve_default=False,
        ),
    ]
