# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-27 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0011_submitreview_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitreview',
            name='section',
            field=models.CharField(max_length=20),
        ),
    ]
